### ISSUE TITLE
how to recompile nvidia-vgpu-vfio with NV_KVM_MIGRATION_UAPI ?

### ISSUE THREAD

**Issue by aderumier** [mbilker/vgpu_unlock-rs#15] opened 2022-08-16 14:45 UTC
Hi,
I'm currently working to add vgpu live migration on proxmox.

I have seen in your doc that nvidia-vgpu-vfio need to be recompiled with NV_KVM_MIGRATION_UAPI=1.

Can you tell me how we can send this variable when building dmks driver ?

**Comment by aderumier** [comment] 2022-08-16 18:02
mmm, it seem that the option has been removed in 510.85.03, 
```
    if (event_type == NV_VFIO_VGPU_EVENT_MIGRATION_STATE) {
#if defined(NV_VFIO_DEVICE_MIGRATION_HAS_START_PFN)
        vgpu_dev->migration_enabled = NV_TRUE;
        NV_VGPU_DEV_LOG(VGPU_ERR, vgpu_dev->mdev,
                        "vGPU migration enabled with v3.2 Kernel UAPI\n");
#else
        NV_VGPU_DEV_LOG(VGPU_ERR, vgpu_dev->mdev,
                        "vGPU migration disabled\n");
#endif
```

but exist in previous 460.73.01.
```
  #if defined(NV_VFIO_DEVICE_MIGRATION_HAS_START_PFN)
        vgpu_dev->migration_enabled = NV_TRUE;
        NV_VGPU_DEV_LOG(VGPU_ERR, vgpu_dev->mdev,
                        "vGPU migration enabled with v3.2 Kernel UAPI\n");
  #elif defined(NV_KVM_MIGRATION_UAPI)
        vgpu_dev->migration_enabled = NV_TRUE;
        NV_VGPU_DEV_LOG(VGPU_ERR, vgpu_dev->mdev,
                        "vGPU migration enabled with upstreamed Kernel UAPI\n");
  #else
        NV_VGPU_DEV_LOG(VGPU_ERR, vgpu_dev->mdev,
                        "vGPU migration disabled\n");

``

with last version, with default compilation,
kernel send a 
``
[nvidia-vgpu-vfio] 00000000-0000-0000-0000-000000000101: vGPU migration disabled
``
but vgpu-mgr service show

```
notice: vmiop_log: (0x0): vGPU migration enabled
```

So, I'm don't known if it's enable or not. (kernel log seem to said that old path start_pfn is not used).


but when I'm trying to live migrate a qemu 6.2 machine with vfio x-enable-migration=on

```
: -device vfio-pci,x-enable-migration=on,sysfsdev=/sys/bus/pci/devices/0000:02:00.0/00000000-0000-0000-0000-000000000101,id=hostpci0,bus=pci.0,addr=0x10
``

I got

```VM 101 qmp command 'migrate' failed - VFIO device doesn't support migration"```

**Comment by mbilker** [comment] 2022-08-24 12:08
Ahh, so it was removed. That kind of sucks, but it was to be expected.

**Comment by mbilker** [comment] 2022-08-24 12:44
Ok, NVIDIA documented how the `NV_VFIO_DEVICE_MIGRATION_HAS_START_PFN` flag is set in `conftest.sh`. It requires specific support to be in the kernel for it to work. It appears NVIDIA redid their approach to be based off what they sent upstream for inclusion into the mainline Linux kernel.

**Comment by aderumier** [comment] 2022-08-24 20:35
ok thanks !

I can get live migration working with qemu 6.2/7.0 with  NV_KVM_MIGRATION_UAPI with old driver.

I'll try with NV_VFIO_DEVICE_MIGRATION_HAS_START_PFN with newer driver to see if it's working fine too with kernel 5.15.  

(I'm currently working to add live vgpu support to proxmox hypervisor)

**Comment by theonlyfoxy** [comment] 2022-08-29 15:23
> ok thanks !
> 
> I can get live migration working with qemu 6.2/7.0 with NV_KVM_MIGRATION_UAPI with old driver.
> 
> I'll try with NV_VFIO_DEVICE_MIGRATION_HAS_START_PFN with newer driver to see if it's working fine too with kernel 5.15.
> 
> (I'm currently working to add live vgpu support to proxmox hypervisor)

Hi. Could you make it work with 510 driver?

**Comment by aderumier** [comment] 2022-08-29 15:36
NV_KVM_MIGRATION_UAPI is still present in  510.73.06

https://github.com/VGPU-Community-D....1/NVIDIA-Linux-x86_64-510.73.06-vgpu-kvm.run

but seem to be removed from  510.85.03

(I don't known if they have forget to add support to this version ?  I have tried with NV_VFIO_DEVICE_MIGRATION_HAS_START_PFN, but it's not compatible with current kernel/qemu implementation)

**Comment by theonlyfoxy** [comment] 2022-08-29 15:49
so live migration works without issue in 510.73.06 driver?

**Comment by aderumier** [comment] 2022-08-29 18:17
@theonlyfoxy 

I don't have tested live migration with 510.73.06 yet.

**Comment by theonlyfoxy** [comment] 2022-08-31 12:46
> @theonlyfoxy
> 
> I don't have tested live migration with 510.73.06 yet.

I have tried and it after saving the vm, When i try to loadvm I get the following error:
qemu-system-x86_64: vfio_region_read(60b0a8e4-1696-4668-badf-9e43a8b34d9d:region0+0x9410, 4) failed: Bad address

not sure if the issue is with driver version tho.

**Comment by aderumier** [comment] 2022-09-01 06:44
> > @theonlyfoxy
> > I don't have tested live migration with 510.73.06 yet.
> 
> I have tried it and after saving the vm, When i try to loadvm I get the following error: qemu-system-x86_64: vfio_region_read(60b0a8e4-1696-4668-badf-9e43a8b34d9d:region0+0x9410, 4) failed: Bad address
> 
> not sure if the issue is with driver version tho.

mmm, so it's seem to be enabled. (or migration whould have hanged with another error message like" vfio migration not enabled...don't remember exactly'.   I never have seen this one.  I'll try to test it next week.

**Comment by susadmin** [comment] 2022-12-05 18:48
Hi, just wondering if there is any update on this? It would great to get it working with the new 15.0 (525.60.12) patch.

**Comment by aderumier** [comment] 2022-12-07 07:05
Hi,
I have looked at 525.60.12, 

NV_KVM_MIGRATION_UAPI (missing from last version), has been replaced by NV_VFIO_DEVICE_MIG_STATE_PRESENT

```
    if (event_type == NV_VFIO_VGPU_EVENT_MIGRATION_STATE) {
#if defined(NV_VFIO_DEVICE_MIGRATION_HAS_START_PFN)
        vgpu_dev->migration_enabled = NV_TRUE;
        NV_VGPU_DEV_LOG(VGPU_ERR, vgpu_dev,
                        "vGPU migration enabled with v3.2 Kernel UAPI\n");
#elif defined(NV_VFIO_DEVICE_MIG_STATE_PRESENT)
        vgpu_dev->migration_enabled = NV_TRUE;
        NV_VGPU_DEV_LOG(VGPU_ERR, vgpu_dev,
                        "vGPU migration enabled with upstream V2 migration protocol\n");
#else
        NV_VGPU_DEV_LOG(VGPU_ERR, vgpu_dev,
                        "vGPU migration disabled\n");
#endif
    }
```

**Comment by susadmin** [comment] 2022-12-08 19:46
Thanks very much for this. So what would be the right way way to compile this? 
Is it as easy as adding: NV_VFIO_DEVICE_MIG_STATE_PRESENT=1 to kernel/conftest.sh?

Thanks for all your help.

**Comment by aderumier** [comment] 2022-12-09 07:22
I don't have tested it yet, but with previous NV_KVM_MIGRATION_UAPI,
it was working with adding in

kernel/nvidia-vgpu-vfio/nvidia-vgpu-vfio.Kbuild

NV_KVM_MIGRATION_UAPI=1


(tested on proxmox with a live migration)



So, it should be the same.  (maybe it's working too in conftest.sh).

**Comment by susadmin** [comment] 2022-12-09 17:13
Hi, Just to let you know, I added NV_VFIO_DEVICE_MIG_STATE_PRESENT=1 to kernel/nvidia-vgpu-vfio/nvidia-vgpu-vfio.Kbuild as you suggested and it is working fine with NVIDIA-GRID-Linux-KVM-525.60.12.

Thanks 0:)

**Comment by CornHead764** [comment] 2022-12-29 06:35
@susadmin 

Was there anything else you needed to do recompile nvidia-vgpu-vfio with NV_VFIO_DEVICE_MIG_STATE_PRESENT=1 besides just putting it in the kernel/nvidia-vgpu-vfio/nvidia-vgpu-vfio.Kbuild file?

I'm trying to replicate this setup with NVIDIA-Linux-x86_64-525.60.12-vgpu-kvm on the latest Proxmox build, and no matter what I try, the kernel driver just doesn't seem to take NV_VFIO_DEVICE_MIG_STATE_PRESENT into consideration when building. dmesg still shows vGPU migration disabled.

If all you did was add that line to the Kbuild file, would you mind posting a copy/screenshot of the edit? This feels like it should be a simple change, but it just doesn't want to cooperate.

**Comment by yubo-li** [comment] 2023-03-03 03:04
@CornHead764 Have you solved the problem yet?
I'm also trying to replicate this but get the same issue. I found in conftest.sh that NV_VFIO_DEVICE_MIG_STATE_PRESENT requires a kernel patch in v5.18, but I don't have environment on hand. This could be the reason that  NV_VFIO_DEVICE_MIG_STATE_PRESENT does not take effect.
```
        vfio_device_mig_state)
            #
            # Determine if vfio_device_mig_state enum is present or not
            #
            # Added by commit 115dcec65f61d ("vfio: Define device
            # migration protocol v2") in v5.18
            #
            CODE="
            #include <linux/pci.h>
            #include <linux/vfio.h>
            enum vfio_device_mig_state device_state;
            "

            compile_check_conftest "$CODE" "NV_VFIO_DEVICE_MIG_STATE_PRESENT" "" "types"
```

**Comment by CornHead764** [comment] 2023-03-03 03:07
@yubo-li 

Unfortunately I have not. I lost track of this project as other things came up. Best of luck, and I'll be keeping an eye on this thread for when I get back to it!

**Comment by yubo-li** [comment] 2023-04-26 06:21
Thanks @CornHead764 , will keep updating here if I get any progress.

**Comment by yubo-li** [comment] 2023-04-26 06:25
@susadmin Have you succeeded in vGPU live migration with NVIDIA-GRID-Linux-KVM-525.60.12? Could you share your linux kernel version and card name (Tesla A100, etc.) for me? Thanks a lot!

**Comment by susadmin** [comment] 2023-04-26 09:16
Hi, it's some time since I visited this issue as the need has gone away for me. I originally wanted this feature to enable live snapshots on my Proxmox host. Some time ago, I upgraded my drivers to 525.85.07 and everything seems very stable (using the patched driver from Polloloco). Hope that helps.

**Comment by yubo-li** [comment] 2023-05-15 10:33
Thanks for your helpful reply!

**Comment by mbilker** [comment] 2024-05-01 20:23
I am closing this because the migration API is more feature complete in newer vGPU KVM host versions and there is better upstream support in Linux. Please do not hesitate to comment on this issue if there are still issues.

**Closed by mbilker** 2024-05-01 20:23 UTC
