### ISSUE TITLE
RTX 2060 In proxmox 7.3 not work

### ISSUE THREAD

**Issue by ranydb** [mbilker/vgpu_unlock-rs#29] opened 2023-02-13 11:52 UTC
```
root@sm1:~# journalctl -u  nvidia-vgpud
-- Journal begins at Sat 2022-07-02 00:18:51 CST, ends at Mon 2023-02-13 19:45:06 CST. --
Feb 13 18:44:27 sm1 systemd[1]: Starting NVIDIA vGPU Daemon...
Feb 13 18:44:27 sm1 nvidia-vgpud[2009]: Verbose syslog connection opened
Feb 13 18:44:27 sm1 nvidia-vgpud[2009]: Started (2009)
Feb 13 18:44:27 sm1 systemd[1]: Started NVIDIA vGPU Daemon.
Feb 13 18:44:27 sm1 nvidia-vgpud[2009]: Global settings:
Feb 13 18:44:27 sm1 nvidia-vgpud[2009]: Size: 16
                                        Version 1
Feb 13 18:44:27 sm1 nvidia-vgpud[2009]: Homogeneous vGPUs: 1
Feb 13 18:44:27 sm1 nvidia-vgpud[2009]: vGPU types: 653
Feb 13 18:44:27 sm1 nvidia-vgpud[2009]:
Feb 13 18:44:28 sm1 nvidia-vgpud[2009]: pciId of gpu [0]: 0:1:0:0
Feb 13 18:44:28 sm1 nvidia-vgpud[2009]: GPU not supported by vGPU at PCI Id: 0:1:0:0 DevID: 0x10de / 0x1e89 / 0x10de / >
Feb 13 18:44:28 sm1 nvidia-vgpud[2009]: error: failed to send vGPU configuration info to RM: 6
Feb 13 18:44:28 sm1 nvidia-vgpud[2009]: PID file unlocked.
Feb 13 18:44:28 sm1 nvidia-vgpud[2009]: PID file closed.
Feb 13 18:44:28 sm1 nvidia-vgpud[2009]: Shutdown (2009)
Feb 13 18:44:28 sm1 systemd[1]: nvidia-vgpud.service: Main process exited, code=exited, status=6/NOTCONFIGURED
Feb 13 18:44:28 sm1 systemd[1]: nvidia-vgpud.service: Failed with result 'exit-code'.
-- Boot 177f81910c4542cb86de3ae6b863f3b2 --
Feb 13 18:56:11 sm1 systemd[1]: Starting NVIDIA vGPU Daemon...
Feb 13 18:56:11 sm1 nvidia-vgpud[2003]: Verbose syslog connection opened
Feb 13 18:56:11 sm1 nvidia-vgpud[2003]: Started (2003)
Feb 13 18:56:11 sm1 systemd[1]: Started NVIDIA vGPU Daemon.
Feb 13 18:56:11 sm1 nvidia-vgpud[2003]: Global settings:
Feb 13 18:56:11 sm1 nvidia-vgpud[2003]: Size: 16
                                        Version 1
Feb 13 18:56:11 sm1 nvidia-vgpud[2003]: Homogeneous vGPUs: 1
```

**Comment by mbilker** [comment] 2023-02-13 16:23
Is the `LD_PRELOAD` environment variable set for the `nvidia-vgpud.service` unit as per the Installation section in the README file?

**Comment by susadmin** [comment] 2023-02-13 19:24
works fine for me 0:)

**Comment by mbilker** [comment] 2023-03-27 04:50
Closed assuming the original reporter figured out what is wrong and has not followed up here saying they did. If the issue is still present, then do not hesitate to report here that you are still having trouble with your RTX 2060.

**Closed** 2023-03-27 04:49 UTC
